name: Run Python Script

on:
  workflow_dispatch: 
    # push: 
    # schedule:
    #   - cron: "*/5 * * * *"

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8 
      - name: Run the script
        run: python index.py
